env:
  PRIVATE: "ENCRYPTED[6e039c2e8c579ec9e460d0fa9479b98fb2a5a7b10115aa3f8bb95e3c431088d4a814f14e61ece695cd98f60690adf0b1"
  PUBLIC: "ENCRYPTED[ac5f8747b660e9995fb5366beb8f65c974175f61454123a0cae6d4b718c1f62afee02b69fa35c5808b9ec60c174b4552"

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  container:
    image: archlinux:latest
    cpu: 6
    memory: 16GB

setup_pacman:
  - rm -rf /etc/pacman.d/gnupg
  - pacman-key --init
  - pacman-key --populate
  - echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" | tee -a /etc/pacman.conf
  - pacman --noconfirm --needed -Syy reflector rsync curl wget git-lfs openssh base-devel devtools sudo git lib32-readline lib32-zlib namcap fakeroot audit grep diffutils
  - useradd -m -d /home/builder -s /bin/bash -G wheel builder
  - echo -e "%wheel ALL=(ALL:ALL) NOPASSWD: ALL" | tee -a /etc/sudoers
  - echo "builder ALL=(ALL) NOPASSWD: ALL" | tee -a /etc/sudoers
  - chown -R builder:builder /home/builder/
  - cd /home/builder
  - sudo -u builder bash -c 'mkdir -p .ssh'
  - sudo -u builder bash -c 'echo "$PRIVATE" > .ssh/id_rsa'
  - sudo -u builder bash -c 'echo "$PUBLIC" > .ssh/id_rsa.pub'
  - sudo -u builder bash -c 'chmod 600 .ssh/id_rsa'
  - sudo -u builder bash -c 'chmod 600 .ssh/id_rsa.pub'
  - sudo -u builder bash -c 'ssh-keyscan github.com >> .ssh/known_hosts'

Build_pkg:
  - sudo -u builder bash -c 'cd /home/builder'
  - sudo -u builder bash -c 'ls -la /home/builder'
  - sudo -u builder bash -c 'pwd'
  - sudo -u builder bash -c 'find .'
  - sudo -u builder bash -c 'sudo chown -R builder:builder .*'
  - sudo -u builder bash -c 'chown -R builder:builder .*''
  - sudo -u builder bash -c 'git clone https://aur.archlinux.org/yay-bin.git'
  - sudo -u builder bash -c 'chown -R builder:builder .*'
  - sudo -u builder bash -c 'cd yay-bin'
  - sudo -u builder bash -c 'makepkg -sci --noconfirm --needed --noprogressbar --skippgpcheck'
  - sudo -u builder bash -c 'cd /home/builder'
  - sudo -u builder bash -c 'rm -rf yay-bin*'
  - sudo -u builder bash -c 'git clone git@github.com:MikuX-Dev/archfiery-pkgbuild.git'
  - sudo -u builder bash -c 'chown -R builder:builder .*'
  - sudo -u builder bash -c 'cd archfiery-pkgbuild/'
  - sudo -u builder bash -c 'chmod +x *.sh'
  - sudo -u builder bash -c './build.sh'

  - sudo -u builder bash -c 'cd /home/builder/archfiery-pkgbuild/'
  - sudo -u builder bash -c 'git clone git@github.com:MikuX-Dev/archfiery-repo.git /home/builder/archfiery-repo'
  - sudo -u builder bash -c './push.sh'
