task:
  name: pkg-build
  only_if: $CIRRUS_BRANCH == 'main'
  cron: "0 8 */4 * *"
  timeout_in: 120m
  container:
    image: archlinux:latest
    cpu: 4
    memory: 12G
  import_ssh_key_script: |
    pacman-key --init
    pacman-key --populate

    if grep -q "\[multilib\]" /etc/pacman.conf; then \
      sed -i '/^\[multilib\]/,/Include = \/etc\/pacman.d\/mirrorlist/ s/^#//' /etc/pacman.conf; \
    else \
      echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" | tee -a /etc/pacman.conf; \
    fi

    pacman --noconfirm -Syyu reflector rsync curl wget git-lfs openssh base-devel devtools sudo git lib32-readline lib32-zlib namcap fakeroot audit grep diffutils parallel

    useradd -m -d /home/builder -s /bin/bash -G wheel builder
    sed -i 's/^# %wheel ALL=(ALL:ALL) NOPASSWD: ALL/%wheel ALL=(ALL:ALL) NOPASSWD: ALL/g' /etc/sudoers
    echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
    chown -R builder:builder /home/builder/

    cd /home/builder
    sudo -u builder bash -c '
    sudo pacman -Syyu --noconfirm --needed --noprogressbar
    mkdir -p /home/builder/.ssh
    sudo chown -R builder:builder /home/builder/.ssh
    chmod 700 /home/builder/.ssh
    touch /home/builder/.ssh/config
    echo "-----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACD0F1z9s53prcpxeTJFByv5nKGQjKkqSTxUy2h+ky/K9gAAAKCnkBUJp5AV
    CQAAAAtzc2gtZWQyNTUxOQAAACD0F1z9s53prcpxeTJFByv5nKGQjKkqSTxUy2h+ky/K9g
    AAAEDVOvaV9Bv+dO5odjD7tStP4lA1fOTh6/yYQMGp2LjSIPQXXP2znemtynF5MkUHK/mc
    oZCMqSpJPFTLaH6TL8r2AAAAGWFiaW5pc2hhbnRoMzQ2NEBnbWFpbC5jb20BAgME
    -----END OPENSSH PRIVATE KEY-----" > /home/builder/.ssh/github_ed
    echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPQXXP2znemtynF5MkUHK/mcoZCMqSpJPFTLaH6TL8r2 abinishanth3464@gmail.com" > /home/builder/.ssh/github_ed.pub
    chmod 600 /home/builder/.ssh/github_ed
    echo -e "Host github.com\n\tForwardAgent yes\n\tAddKeysToAgent yes\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n\tIdentityFile /home/builder/.ssh/github_ed" >> /home/builder/.ssh/config
    eval "$(ssh-agent -s)"
    echo "$SSH_AUTH_SOCK"
    echo "github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
    github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
    github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=" > /home/builder/.ssh/known_hosts
    ssh-keyscan github.com >> /home/builder/.ssh/known_hosts
    cat /home/builder/.ssh/config
    cat /home/builder/.ssh/github_ed
    cat /home/builder/.ssh/github_ed.pub
    sudo chown -R builder:builder /home/builder
    ssh-add /home/builder/.ssh/github_ed
    ssh -vT git@github.com
    '
  build_pkg_script: |
    cd /home/builder
    sudo -u builder bash -c '
    sudo chown -R builder:builder .*
    git clone https://aur.archlinux.org/paru-bin.git
    sudo chown -R builder:builder .*
    cd paru-bin
    makepkg -sci --noconfirm --needed --noprogressbar --skippgpcheck
    cd -
    rm -rf paru-bin*
    git clone git@github.com:MikuX-Dev/archfiery-pkgbuild.git
    sudo chown -R builder:builder .*
    cd archfiery-pkgbuild/
    chmod +x *.sh
    ./build.sh
    '
  clone_repo_and_commit_script: |
    cd /home/builder/archfiery-pkgbuild/
    sudo -u builder bash -c '
    git clone git@github.com:MikuX-Dev/archfiery-repo.git /home/builder/archfiery-repo
    ./push.sh
    '