version: 2.1

jobs:
  build:
    docker:
      - image: archlinux:latest
    steps:
      - checkout
      - run:
          name: Setup pacman
          command: |
            rm -rf /etc/pacman.d/gnupg
            pacman-key --init
            pacman-key --populate

            if grep -q "\[multilib\]" /etc/pacman.conf; then \
              sed -i '/^\[multilib\]/,/Include = \/etc\/pacman.d\/mirrorlist/ s/^#//' /etc/pacman.conf; \
            else \
              echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" | tee -a /etc/pacman.conf; \
            fi

            pacman --noconfirm --needed -Syy reflector rsync curl wget git-lfs openssh base-devel devtools sudo git lib32-readline lib32-zlib namcap fakeroot audit grep diffutils

            useradd -m -d /home/builder -s /bin/bash -G wheel builder
            sed -i 's/^# %wheel ALL=(ALL:ALL) NOPASSWD: ALL/%wheel ALL=(ALL:ALL) NOPASSWD: ALL/g' /etc/sudoers
            echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
            chown -R builder:builder /home/builder/
      - run:
          name: Set up SSH key
          command: |
            cd /home/builder/
            sudo -u builder bash -c '
            mkdir -p .ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > .ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY_PUB }}" > .ssh/id_rsa.pub
            chmod 600 .ssh/id_rsa
            chmod 600 .ssh/id_rsa.pub
            ssh-keyscan github.com >> .ssh/known_hosts
            '
      - run:
          name: Build pkg
          command: |
            sudo -u builder bash -c '
            cd /home/builder
            ls -la /home/builder
            pwd
            find .
            sudo chown -R builder:builder .*
            chown -R builder:builder .*
            git clone https://aur.archlinux.org/yay-bin.git
            chown -R builder:builder .*
            cd yay-bin
            makepkg -sci --noconfirm --needed --noprogressbar --skippgpcheck
            cd /home/builder
            rm -rf yay-bin*
            git clone git@github.com:MikuX-Dev/archfiery-pkgbuild.git
            chown -R builder:builder .*
            cd archfiery-pkgbuild/
            chmod +x *.sh
            ./build.sh
            '
      - run:
          name: Clone Repo and copy pkg and Commit and Push Changes
          command: |
            sudo -u builder bash -c '
            cd /home/builder
            git clone git@github.com:MikuX-Dev/archfiery-repo.git /home/builder/archfiery-repo
            ./push.sh
            '

workflows:
  build_pkg:
    jobs:
      - build
