# .github/workflows/package.yml

name: Build Package 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    container: 
      image: archlinux:latest
      # options: --user builder

    steps:

    # - name: Add builder user
    #   run: |  
    #     pacman -Syu --noconfirm sudo
    #     useradd -m -s /bin/bash -G wheel builder
    #     sed -i 's/^# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/g' /etc/sudoers

    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo pacman-key --init
        sudo pacman-key --populate
        sudo pacman -Syyu --noconfirm sudo base-devel git curl openssh make archiso mkinitcpio-archiso

    - name: Import SSH key  
      env:  
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock  
      run: |
        mkdir -p ~/.ssh
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add - > /dev/null

    - name: Build packages
      run: |
        ls -al; ls ../
        for dir in x86_64/*/; do 
          cd $dir
          NAME=${dir%*/}
          curl -sSL https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=$NAME > ./PKGBUILD
          makepkg --syncdeps --needed --noconfirm --noprogressbar --nocheck
          cd -  
        done

    - name: Push packages
      run: |
        REMOTE_REPO="ssh://git@github.com/MikuX-Dev/archfiery-repo.git"
        git clone $REMOTE_REPO out

        for dir in x86_64/*/; do
          cp $dir/*.* out/x86_64/
        done

        cd out
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Add packages built from ${GITHUB_REF##*/}"
        git push
