name: Build Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 8 */4 * *"  # Every 4 days

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        pacman-key --init && pacman-key --populate
        pacman --noconfirm --noprogressbar --needed -Syy make openssh

    - name: Import SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY_PUB }}" > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa.pub
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Create User
      run: |
        mkdir -p /startdir /build
        groupadd -g 1000 user
        useradd -m -d /build -u 1000 -g 1000 -G wheel -s /bin/bash user && \
        chown -R user:user /startdir /build && \
        echo 'user ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
        # useradd -r -m -s /bin/bash -G wheel user && \
        # sed -i 's/^# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/g' /etc/sudoers

    - name: Build Packages
      run: |
        chown -R user:user /home/user/
        chown -R user:user *
        chmod 755 build-packages.sh
        su -s /bin/bash user -c "./build-packages.sh"

    - name: Clone Repository
      run: |
        git clone git@github.com:MikuX-Dev/archfiery-repo.git

    - name: Copy Packages to Repository
      run: |
        # cp -r x86_64/* archfiery-repo/x86_64/
        for dir in x86_64/*/; do
          cp -r "$dir"/*.tar.* archfiery-repo/x86_64/
        done

    - name: Commit and Push Changes
      run: |
        cd archfiery-repo
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "Add built packages"
        git push
