# .github/workflows/package.yml

name: Build Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 8 */4 * *"  # Every 4 days

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: mikuxdev/archiso:latest

    steps:
    - uses: actions/checkout@v3

    - name: Import SSH key
      run: |
        mkdir ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY_PUB }}" > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa.pub
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Build packages
      run: |
        pacman-key --init && pacman-key --populate
        pacman --noconfirm --noprogressbar --needed -Syy

        # su -l user

        # Add builder User

        useradd -r -m -s /bin/bash -G wheel user && \
        sed -i 's/^# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/g' /etc/sudoers

        chown -R user:user /home/user/

        chown -R user:user *
        chmod 755 build-packages.sh
        ./build-packages.sh

        # for dir in x86_64/*/; do
        #   cd "$dir"
        #     makepkg -sf --noconfirm --needed --noprogressbar
        #   cd -
        # done

    - name: Push packages
      run: |
        git clone git@github.com:MikuX-Dev/archfiery-repo.git

        for dir in x86_64/*/; do
          cp -r "$dir"/*.tar.* archfiery-repo/x86_64/
        done

        cd archfiery-repo/

        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Add packages built from ${GITHUB_REF##*/}"
        git push
