# .github/workflows/package.yml

name: Build Package 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    container: 
      image: archlinux
      options: --user builder

    steps:
    - uses: actions/checkout@v3

    - name: Add builder user  
      run: |
        groupadd -r builder && useradd -m -r -g builder builder

    - name: Install dependencies
      run: |
        sudo pacman-key --init; sudo pacman-key --populate
        sudo pacman -Syyu --noconfirm
        sudo pacman -S --noconfirm base-devel git curl openssh make archiso mkinitcpio-archiso
      
    - name: Import SSH key  
      env:  
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock  
      run: |
        mkdir -p ~/.ssh
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add - > /dev/null

    - name: Build packages
      run: |
        for dir in x86_64/*/; do
          cd $dir
          NAME=${dir%*/}
          curl -sSL https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=$NAME > ./PKGBUILD
          makepkg --syncdeps --needed --noconfirm --noprogressbar --nocheck
          cd -
        done

    - name: Push packages
      run: |
        REMOTE_REPO="ssh://git@github.com/MikuX-Dev/archfiery-repo.git"
        git clone $REMOTE_REPO out
      
        for dir in x86_64/*/; do
          cp $dir/*.zst out/x86_64/
        done
      
        cd out
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Add packages built from ${GITHUB_REF##*/}"
        git push
