# .github/workflows/package.yml

name: Build Package 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    container: 
      image: archlinux:latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sed -i "s/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g" /etc/locale.gen
        locale-gen
        echo "LANG=en_US.UTF-8" > /etc/locale.conf
        echo 'KEYMAP=us' > /etc/vconsole.conf

        pacman-key --init
        pacman-key --populate
        pacman -Syyu --noconfirm base-devel git curl openssh make archiso mkinitcpio-archiso docker docker-buildx

    - name: Import SSH key
      run: |
        mkdir ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa

    - name: Build packages
      run: |
        mkdir output/

        docker build -t archpkgb -f Dockerfile .
        docker run -i -d --rm -v $(pwd):/tmp archpkgb

    - name: Push packages
      run: |
        ./push.sh
