# .github/workflows/package.yml

name: Build Package 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    container: 
      image: archlinux:latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sed -i "s/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g" /etc/locale.gen
        locale-gen
        echo "LANG=en_US.UTF-8" > /etc/locale.conf
        echo 'KEYMAP=us' > /etc/vconsole.conf

        pacman-key --init
        pacman-key --populate
        pacman -Syyu --noconfirm base-devel git curl openssh make archiso mkinitcpio-archiso docker docker-buildx

    - name: Import SSH key  
      env:  
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock  
      run: |
        mkdir -p ~/.ssh
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add - > /dev/null

    - name: Build packages
      run: |
        ls -al; ls ../
        for dir in x86_64/*/; do 
          cd $dir
          NAME=${dir%*/}
          curl -sSL https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h="$NAME" > ./PKGBUILD
          docker build -t builder -f docker/Dockerfile $dir
          docker run --rm builder
          cd -
        done

    - name: Push packages
      run: |
        REMOTE_REPO="ssh://git@github.com/MikuX-Dev/archfiery-repo.git"
        git clone $REMOTE_REPO out/

        for dir in x86_64/*/; do
          cp $dir/*.* out/x86_64/
        done

        cd out/
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Add packages built from ${GITHUB_REF##*/}"
        git push
