name: pkg-aur

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 8 */4 * *"  # Every 4 days

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: setup pacman
      run: |
          pacman-key --init
          pacman --noconfirm -Syy archlinux-keyring
          pacman --noconfirm --needed -Sy reflector rsync curl wget git-lfs && \
          reflector --latest 21 -f 21 -n 21 --age 21 --protocol https --download-timeout 55 --sort rate --save /etc/pacman.d/mirrorlist && \
          pacman --noconfirm --needed -Syy openssh base-devel devtools sudo git namcap fakeroot audit grep diffutils

          useradd -m -d /home/builder -s /bin/bash -G wheel builder && \
          sed -i 's/^# %wheel ALL=(ALL:ALL) NOPASSWD: ALL/%wheel ALL=(ALL:ALL) NOPASSWD: ALL/g' /etc/sudoers && \
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

          chown -R builder:builder /home/builder/

    - name: Import SSH key
      run: |
        cd /home/builder
        sudo -u builder bash -c '
        mkdir -p .ssh /tmp/pkg-build /tmp/output/large /tmp/output/small
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > .ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY_PUB }}" > .ssh/id_rsa.pub
        chmod 600 .ssh/id_rsa
        chmod 600 .ssh/id_rsa.pub
        ssh-keyscan github.com >> .ssh/known_hosts
        '

    - name: Build pkg
      run: |
        sudo -u builder bash -c '
        cd /home/builder
        ls -la /home/builder
        pwd
        find .
        git clone git@github.com:MikuX-Dev/archfiery-pkgbuild.git
        chown -R builder:builder .*
        cd archfiery-pkgbuild/
        chmod +x *.sh
        chown -R builder:builder .*

        if [ -d "/github" ]; then
          chown -R builder:builder /github/workspace /github/home
        fi

        packages=("appmenu-gtk-module-git" "appmenu-qt4" "bluez-firmware" "brave-bin" "caffeine-ng" "dolphin-megasync-bin" "downgrade" "eww-x11" "fancontrol-gui" "firebuild" "gtk3-nocsd-git" "libdbusmenu-glib" "libdbusmenu-gtk2" "libdbusmenu-gtk3" "mkinitcpio-firmware" "mkinitcpio-numlock" "mugshot" "nbfc" "obsidian-bin" "ocs-url" "repoctl" "rtl8821ce-dkms-git" "rtw89-dkms-git" "stacer-bin" "tela-icon-theme" "thunar-extended" "thunar-megasync-bin" "thunar-secure-delete" "thunar-shares-plugin" "thunar-vcs-plugin" "universal-android-debloater-bin" "vala-panel-appmenu-common-git" "vala-panel-appmenu-registrar-git" "vala-panel-appmenu-xfce-git" "xfce4-docklike-plugin" "xfce4-panel-profiles" "zsh-theme-powerlevel10k-git" "tlpui" "simplescreenrecorder" "visual-studio-code-bin" "ncurses5-compat-libs" "lib32-ncurses5-compat-libs" "aosp-devel" "xml2" "lineageos-devel" "btrfs-assistant" "snapper-gui-git" "firmware-manager" "yay-bin")

        for package in "${packages[@]}"; do
          git clone https://aur.archlinux.org/"$package".git /tmp/pkg-build/"$package"
          cd /tmp/pkg-build/"$package" || exit
          makepkg -cs --noconfirm --needed --noprogressbar
          pkgsize=$(du -sh *.pkg.tar.zst | cut -f1)
          if [[ $pkgsize > 100*1024*1024 ]]; then
            echo "$package >= 100MB"
            mv *.pkg.tar.zst /tmp/output/large
          else
            mv *.pkg.tar.zst /tmp/output/small
          fi
          cd -
        done
        '

    - name: Clone Repo and copy pkg and Commit and Push Changes
      run: |
        cd /home/builder
        sudo -u builder bash -c '
        git clone git@github.com:MikuX-Dev/archfiery-repo.git
        cd archfiery-repo/
        git lfs install
        echo "*.zst filter=lfs diff=lfs merge=lfs -text" > .gitattributes

        cd x86_64/

        packages=("appmenu-gtk-module-git" "appmenu-qt4" "bluez-firmware" "brave-bin" "caffeine-ng" "dolphin-megasync-bin" "downgrade" "eww-x11" "fancontrol-gui" "firebuild" "gtk3-nocsd-git" "libdbusmenu-glib" "libdbusmenu-gtk2" "libdbusmenu-gtk3" "mkinitcpio-firmware" "mkinitcpio-numlock" "mugshot" "nbfc" "obsidian-bin" "ocs-url" "repoctl" "rtl8821ce-dkms-git" "rtw89-dkms-git" "stacer-bin" "tela-icon-theme" "thunar-extended" "thunar-megasync-bin" "thunar-secure-delete" "thunar-shares-plugin" "thunar-vcs-plugin" "universal-android-debloater-bin" "vala-panel-appmenu-common-git" "vala-panel-appmenu-registrar-git" "vala-panel-appmenu-xfce-git" "xfce4-docklike-plugin" "xfce4-panel-profiles" "zsh-theme-powerlevel10k-git" "tlpui" "simplescreenrecorder" "visual-studio-code-bin" "ncurses5-compat-libs" "lib32-ncurses5-compat-libs" "aosp-devel" "xml2" "lineageos-devel" "btrfs-assistant" "snapper-gui-git" "firmware-manager" "yay-bin")

        for package in "${packages[@]}"; do
          rm -rf ./*"$package"*pkg.tar.*
        done

        cp -r /tmp/output/small/* ./

        for pkg in /tmp/output/large/*.zst; do
          filename=$(basename $pkg)
          git lfs track "x86_64/$filename"
        done

        cp -r /tmp/output/large/* ./

        mv .gitattributes /home/builder/archfiery-repo/

        chmod +x ./update-db.sh
        ./update-db.sh

        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "Add built packages"
        git push
        '
