name: pkg-aur

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 8 */4 * *"  # Every 4 days

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: setup pacman
      run: |
          pacman-key --init
          pacman --noconfirm -Syy archlinux-keyring
          pacman --noconfirm --needed -Sy reflector rsync curl wget git-lfs && \
          reflector --latest 21 -f 21 -n 21 --age 21 --protocol https --download-timeout 55 --sort rate --save /etc/pacman.d/mirrorlist && \
          pacman --noconfirm --needed -Syy openssh base-devel devtools sudo git namcap fakeroot audit grep diffutils

          useradd -m -d /home/builder -s /bin/bash -G wheel builder && \
          sed -i 's/^# %wheel ALL=(ALL:ALL) NOPASSWD: ALL/%wheel ALL=(ALL:ALL) NOPASSWD: ALL/g' /etc/sudoers && \
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

          chown -R builder:builder /home/builder/

    - name: Import SSH key
      run: |
        cd /home/builder
        sudo -u builder bash -c '
        mkdir -p .ssh /tmp/pkg-build /home/builder/output-large /home/builder/output-small .cache/pikaur/pkg/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > .ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY_PUB }}" > .ssh/id_rsa.pub
        chmod 600 .ssh/id_rsa
        chmod 600 .ssh/id_rsa.pub
        ssh-keyscan github.com >> .ssh/known_hosts
        '

    - name: Build pkg
      run: |
        sudo -u builder bash -c '
        cd /home/builder
        ls -la /home/builder
        pwd
        find .
        sudo chown -R builder:builder .*
        if [ -d "/github" ]; then
          sudo chown -R builder:builder /github/workspace /github/home
        fi
        cd /home/builder
        curl -O -s https://aur.archlinux.org/cgit/aur.git/snapshot/pikaur.tar.gz
        tar xf pikaur.tar.gz
        cd pikaur
        makepkg -is --skippgpcheck --noconfirm --needed
        cd /home/builder
        rm -rf pikaur
        rm pikaur.tar.gz
        git clone git@github.com:MikuX-Dev/archfiery-pkgbuild.git
        chown -R builder:builder .*
        cd archfiery-pkgbuild/
        chmod +x *.sh
        ./build-aur.sh
        '

    - name: Clone Repo and copy pkg and Commit and Push Changes
      run: |
        cd /home/builder/archfiery-pkgbuild/
        sudo -u builder bash -c '
        git clone git@github.com:MikuX-Dev/archfiery-repo.git /home/builder/archfiery-repo
        ./push-aur.sh
        '
