name: pkg-build

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 8 */4 * *" # Every 4 days

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: setup pacman
        run: |
          rm -rf /etc/pacman.d/gnupg
          pacman-key --init
          pacman-key --populate
          echo -e "\n[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          pacman --noconfirm --needed -Syy reflector rsync curl wget git-lfs openssh base-devel devtools sudo git lib32-readline lib32-zlib namcap fakeroot audit grep diffutils
          useradd -m -d /home/builder -s /bin/bash -G wheel builder
          sed -i 's/^# %wheel ALL=(ALL:ALL) NOPASSWD: ALL/%wheel ALL=(ALL:ALL) NOPASSWD: ALL/g' /etc/sudoers
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builder:builder /home/builder/
      - name: Import SSH key
        run: |
          cd /home/builder
          mkdir -p .ssh
          echo "${{ secrets.KEY }}" > .ssh/id_ed
          echo "${{ secrets.KEY_PUB }}" > .ssh/id_ed.pub
          chmod 600 .ssh/id_ed
          chmod 600 .ssh/id_ed.pub
          eval $(ssh-agent -s)
          echo "Key contents:"
          cat .ssh/id_ed
          ssh-add .ssh/id_ed
          echo "SSH Agent status:"
          ssh-add -l
      - run: |
          sudo -u builder bash -c '
          cd /home/builder
          ls -la /home/builder
          pwd
          find .
          '
      - name: Give permissions
        run: |
          cd /home/builder
          sudo -u builder bash -c '
          if [ -d "/github" ]; then
            sudo chown -R builder:builder /github/workspace /github/home
          fi
          sudo chown -R builder:builder .*
          '
      - name: Build pkg
        run: |
          sudo -u builder bash -c '
          cd /home/builder
          git clone https://aur.archlinux.org/yay-bin.git
          cd yay-bin
          makepkg -sci --noconfirm --needed --noprogressbar --skippgpcheck
          cd /home/builder
          rm -rf yay-bin*
          git clone git@github.com:MikuX-Dev/archfiery-pkgbuild.git
          cd archfiery-pkgbuild/
          chmod +x *.sh
          ./build.sh
          '
      - name: Clone Repo and copy pkg and Commit and Push Changes
        run: |
          sudo -u builder bash -c '
          cd /home/builder/archfiery-pkgbuild/
          git clone git@github.com:MikuX-Dev/archfiery-repo.git /home/builder/archfiery-repo
          ./push.sh
          '
