name: pkg-aur

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 8 */4 * *"  # Every 4 days

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mikuxdev/pkg-aur:latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Import SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY_PUB }}" > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa.pub
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: build docker and run
      run: |
        sudo sed -i '/E_ROOT/d' /usr/bin/makepkg
        sudo chown -R builder:builder .*
        sudo chmod +x pkg-aur.sh && ./pkg-aur.sh

    - name: Clone Repository
      run: |
        git clone git@github.com:MikuX-Dev/archfiery-repo.git

    - name: Copy Packages to Repository
      run: |
        cp -r output/* archfiery-repo/x86_64/

    - name: Commit and Push Changes
      run: |
        cd archfiery-repo
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "Add built packages"
        git push
