name: pkg-aur

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 8 */4 * *"  # Every 4 days

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: setup pacman
      run: |
          pacman-key --init
          pacman --noconfirm -Syy archlinux-keyring
          pacman --noconfirm --needed -Sy reflector rsync curl wget git-lfs && \
          reflector --latest 21 -f 21 -n 21 --age 21 --protocol https --download-timeout 55 --sort rate --save /etc/pacman.d/mirrorlist && \
          pacman --noconfirm --needed -Syy openssh base-devel devtools sudo git namcap fakeroot audit grep diffutils

          useradd -m -d /home/builder -s /bin/bash -G wheel builder && \
          sed -i 's/^# %wheel ALL=(ALL:ALL) NOPASSWD: ALL/%wheel ALL=(ALL:ALL) NOPASSWD: ALL/g' /etc/sudoers && \
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

          chown -R builder:builder /home/builder/

    - name: Import SSH key
      run: |
        cd /home/builder
        sudo -u builder bash -c '
        mkdir -p .ssh /tmp/pkg-build /home/builder/output  /home/builder/output/large  /home/builder/output/small
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > .ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY_PUB }}" > .ssh/id_rsa.pub
        chmod 600 .ssh/id_rsa
        chmod 600 .ssh/id_rsa.pub
        ssh-keyscan github.com >> .ssh/known_hosts
        '

    - name: Build pkg
      run: |
        sudo -u builder bash -c '
        cd /home/builder
        ls -la /home/builder
        pwd
        find .
        git clone git@github.com:MikuX-Dev/archfiery-pkgbuild.git
        chown -R builder:builder .*
        cd archfiery-pkgbuild/
        chmod +x *.sh
        ./build-aur.sh
        '

    - name: Clone Repo and copy pkg and Commit and Push Changes
      run: |
        cd /home/builder
        sudo -u builder bash -c '
        git clone git@github.com:MikuX-Dev/archfiery-repo.git
        cd archfiery-repo/
        git lfs install

        cd x86_64/
        rm -rf ./*.pkg.tar.*

        cp -r /home/builder/output/large/* ./
        git lfs track ./
        mv .gitattributes /home/builder/archfiery-repo/
        cp -r /home/builder/output/small/* ./

        chmod +x ./update-db.sh
        ./update-db.sh

        cd /home/builder/archfiery-repo/
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "Add built packages"
        git push
        '
