name: pkg-aur

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 8 */4 * *"  # Every 4 days

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Prepare
      run: pacmam-key --init && pacman -S archlinux-keyring && pacman -Syyu openssh devtools base-devel --noconfirm --needed

    - name: Import SSH key
      run: |
        mkdir -p ~/.ssh ~/output /tmp/pkg-build
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY_PUB }}" > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa.pub
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    # - uses: addnab/docker-run-action@v3
    #   with:
    #     image: mikuxdev/pkg-aur:latest
    #     options: -v ${{ github.workspace }}:/home/builder:rw
    #     shell: bash
    #     run: |
    - name: Build pkg
      run: |
          ls -la /home/builder
          pwd
          find .
          sudo chown -R builder:builder .*
          sudo chmod +x pkg-aur.sh
          sudo chown -R builder:builder .*

          if [ -d "/github" ]; then
            sudo chown -R builder:builder /github/workspace /github/home
          fi

          packages=("btrfs-assistant" "snapper-gui-git" "mkinitcpio-firmware" "firmware-manager" "pikaur" "yay-bin")

          for package in "${packages[@]}"; do
            git clone https://aur.archlinux.org/"$package".git /tmp/pkg-build/"$package"
            cd /tmp/pkg-build/"$package" || exit
            makepkg -csf --noconfirm --needed --noprogressbar
            cp -r /tmp/pkg-build/"$package"/*.pkg.* ../output
            cd ..
          done

    - name: Clone Repo and copy pkg and Commit and Push Changes
      run: |
        git clone git@github.com:MikuX-Dev/archfiery-repo.git
        cp -r output/* archfiery-repo/x86_64/
        cd archfiery-repo
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "Add built packages"
        git push
