name: pkg-aur

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 8 */4 * *"  # Every 4 days

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: setup pacman
      run: |
          pacman-key --init
          pacman --noconfirm -Syy archlinux-keyring
          pacman --noconfirm --needed -Sy reflector rsync curl wget && \
          reflector --latest 21 -f 21 -n 21 --age 21 --protocol https --download-timeout 55 --sort rate --save /etc/pacman.d/mirrorlist && \
          pacman --noconfirm --needed -Syy openssh base-devel devtools sudo git namcap fakeroot audit grep diffutils

          useradd -m -d /home/builder -s /bin/bash -G wheel builder && \
          sed -i 's/^# %wheel ALL=(ALL:ALL) NOPASSWD: ALL/%wheel ALL=(ALL:ALL) NOPASSWD: ALL/g' /etc/sudoers && \
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

          chown -R builder:builder /home/builder/

    - name: Import SSH key
      run: |
        cd /home/builder
        sudo -u builder bash -c '
        mkdir -p .ssh /tmp/pkg-build /tmp/output
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > .ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY_PUB }}" > .ssh/id_rsa.pub
        chmod 600 .ssh/id_rsa
        chmod 600 .ssh/id_rsa.pub
        ssh-keyscan github.com >> .ssh/known_hosts
        '

    # - uses: addnab/docker-run-action@v3
    #   with:
    #     image: mikuxdev/pkg-aur:latest
    #     options: -v ${{ github.workspace }}:/home/builder:rw
    #     shell: bash
    #     run: |
    - name: Build pkg
      run: |
        cd /home/builder
        ls -la /home/builder
        pwd
        find .
        sudo -u builder bash -c 'cp -r ${{ github.workspace }}/.* /home/builder'
        sudo -u builder bash -c 'chown -R builder:builder .*'
        sudo -u builder bash -c 'chmod +x pkg-aur.sh'
        sudo -u builder bash -c 'chown -R builder:builder .*'

        if [ -d "/github" ]; then
        sudo -u builder bash -c 'chown -R builder:builder /github/workspace /github/home'
        fi

        packages=("btrfs-assistant" "snapper-gui-git" "mkinitcpio-firmware" "firmware-manager" "pikaur" "yay-bin")

        for package in "${packages[@]}"; do
          git clone https://aur.archlinux.org/"$package".git /tmp/pkg-build/"$package"
          cd /tmp/pkg-build/"$package" || exit
          makepkg -csf --noconfirm --needed --noprogressbar
          cp -r /tmp/pkg-build/"$package"/*.pkg.* /tmp/output
          cd ..
        done

    - name: Clone Repo and copy pkg and Commit and Push Changes
      run: |
        git clone git@github.com:MikuX-Dev/archfiery-repo.git /home/builder/archfiery-repo
        cp -r /tmp/output/* /home/builder/archfiery-repo/x86_64/
        cd /home/builder/archfiery-repo/
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "Add built packages"
        git push
