name: pkg-build

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 8 */4 * *" # Every 4 days

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mikuxdev/archlinux-pkgbuild:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Import SSH key
        run: |
          cd /home/builder
          sudo -u builder bash -c '
          mkdir -p .ssh
          echo "${{ secrets.KEY }}" > .ssh/id_rsa
          echo "${{ secrets.KEY_PUB }}" > .ssh/id_rsa.pub
          chmod 600 .ssh/id_rsa
          chmod 600 .ssh/id_rsa.pub
          ssh-keyscan github.com >> .ssh/known_hosts
          '
      - name: Build pkg
        run: |
          cd /home/builder
          sudo -u builder bash -c '
          sudo chown -R builder:builder .*
          ls -la /home/builder
          pwd
          find .
          if [ -d "/github" ]; then
            sudo chown -R builder:builder /github/workspace /github/home
          fi
          chown -R builder:builder .*
          git clone https://aur.archlinux.org/paru-bin.git
          git clone https://aur.archlinux.org/yay-bin.git
          chown -R builder:builder .*
          cd paru-bin
          makepkg -sci --noconfirm --needed --noprogressbar --skippgpcheck
          cd -
          cd yay-bin
          makepkg -sci --noconfirm --needed --noprogressbar --skippgpcheck
          cd -
          rm -rf paru-bin* yay-bin*
          git clone git@github.com:MikuX-Dev/archfiery-pkgbuild.git
          chown -R builder:builder .*
          cd archfiery-pkgbuild/
          chmod +x *.sh
          ./build.sh
          '
      - name: Clone Repo and copy pkg and Commit and Push Changes
        run: |
          cd /home/builder
          sudo -u builder bash -c '
          git clone git@github.com:MikuX-Dev/archfiery-repo.git /home/builder/archfiery-repo
          ./push.sh
          '
